# Generated by Django 4.1.1 on 2022-09-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='guilds',
        ),
    ]
