# Generated by Django 4.1.1 on 2022-09-27 19:05

import discordAuth.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0002_remove_discorduser_guilds'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='discorduser',
            managers=[
                ('objects', discordAuth.managers.DiscordUserOauth2Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
