# Generated by Django 4.1.1 on 2022-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0003_alter_discorduser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduser',
            old_name='publics_flags',
            new_name='public_flags',
        ),
    ]
