# Generated by Django 4.1.1 on 2022-09-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0006_rename_publics_flags_discorduser_public_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='guilds',
            field=models.JSONField(null=True),
        ),
    ]
