# Generated by Django 4.1.1 on 2022-09-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0007_discorduser_guilds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discorduser',
            name='guilds',
        ),
    ]
