# Generated by Django 4.1.1 on 2022-09-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0008_remove_discorduser_guilds'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='guilds',
            field=models.JSONField(null=True),
        ),
    ]
