# Generated by Django 4.1.1 on 2022-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0010_alter_discorduser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('token', models.BigIntegerField()),
            ],
        ),
    ]
