# Generated by Django 4.1.1 on 2022-10-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0013_remove_discorduser_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='last_date',
            field=models.DateTimeField(null=True),
        ),
    ]
