# Generated by Django 4.1.1 on 2022-10-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0014_refreshtoken_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='premium_type',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
