# Generated by Django 4.1.1 on 2022-10-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0015_discorduser_premium_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
