# Generated by Django 4.1.1 on 2022-10-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discordAuth', '0016_discorduser_tag_discorduser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='premium_type',
            field=models.IntegerField(null=True),
        ),
    ]
