# Generated by Django 4.1.1 on 2022-11-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordChannelSetup',
        ),
    ]
