# Generated by Django 4.1.1 on 2022-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_disocrdchannelsetup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelSetup',
        ),
    ]
