# Generated by Django 4.1.1 on 2022-11-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_delete_channelsetup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisocrdChannelSetup',
            new_name='DiscordChannelSetup',
        ),
    ]
